name: Verified commits check


author: Nadock


description: Check pushed commits for unverified commits.


branding:
  icon: check
  color: green


inputs:
  github_token:
    description: GitHub token needed to get verified commit information from the GitHub API
    required: True
    default: ${{ github.token }}


runs:
  using: docker
  image: Dockerfile
