name: assign-prs


on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review


jobs:
  assign-prs:
    name: assign PRs
    runs-on: ubuntu-latest
    steps:
      # Pinned to v1.1.1 to avoid action code changing without our consent
      - uses: kentaro-m/auto-assign-action@eea5ee2e4421078bf163287c05e72d162781b30c
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
